name: reservation_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.0.0
  flutter_riverpod: ^2.0.0
  mask_text_input_formatter: ^2.9.0
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
